version: '2'
services:
  elasticsearch-app:
    image: elasticsearch
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://elasticsearch-mysql:3306/elasticsearch?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://elasticsearch-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://elasticsearch-elasticsearch:9200
    ports:
      - 8080:8080
  elasticsearch-mysql:
    extends:
      file: mysql.yml
      service: elasticsearch-mysql
  elasticsearch-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch-elasticsearch
